### ISSUE TITLE
Differences in Version 0.28 and 2.00 when modifying form factors in RK*

### ISSUE THREAD

**Issue by brainygh** [flav-io/flavio#104]
Dear all,

I have noticed a difference in the distribution of RK* when modifying form factors between v 0.28 and v 2.00.

I have plotted the distribution of RK* with the default form factors. I got a flat distribution for the SM, and less suppression in the low q^2 region when introducing a C_9 or C_10, or a combination of the two in both versions as expected.

However, when I increase the value of A_12 to about 1.5 (I understand it should not be this large from the LCSR calculation), I got a flat distribution even when introducing C_9 or C_10 in v0.28. This was not true for v2.00. In contrast, in the current version, when I increase the value of A_0 to some large value, I got a flat distribution(Again, I understand that A_0 should not be this large from the LCSR calculation).

I have attached the plots. I have looked through the changes and did not spot anything that would lead to this. I also tried to compare some relevant files without a clear answer. Could you please help me with that?

Thanks!
[modifiedA0_2.0.pdf](https://github.com/flav-io/flavio/files/4094459/modifiedA0_2.0.pdf)
[modifiedA2_0.28.pdf](https://github.com/flav-io/flavio/files/4094462/modifiedA2_0.28.pdf)

**Comment by DavidMStraub** [comment]
Hi,

I am not aware of a relevant change either. There was only one commit affecting the form factors, 7b9eff362f32a631853ea62e9af75c005d985896, but this was just a refactoring that was supposed to not have any numerical effect (and I believe this is checked through unit tests, at least approximately).

I suggest you first compare the B->K* form factors numerically for the two versions.

If they agree, the problem is either due to other parameters (the default values for several of them changed) or due to numerical imprecision.

To exclude the former, compare the observables for all non-FF parameters equal.

To exclude the latter, I suggest directly comparing the values of the differential branching ratios for fixed lepton flavor (`dBR/dq2(...)`) at fixed `q2`.

**Comment by peterstangl** [comment]
Hi,

in the commit https://github.com/flav-io/flavio/commit/7b9eff362f32a631853ea62e9af75c005d985896, actually some changes have been made concerning `a0_A0` and `a0_A12`, in particular at the following places:
- Line 51 in `flavio/physics/bdecays/formfactors/b_v/bsz.py`:
https://github.com/flav-io/flavio/commit/7b9eff362f32a631853ea62e9af75c005d985896#diff-8da5a9639759303ee8930e81d6becc42L51-R51
- Lines 21-39 in `flavio/physics/bdecays/formfactors/b_v/bsz_parameters.py`:
https://github.com/flav-io/flavio/commit/7b9eff362f32a631853ea62e9af75c005d985896#diff-41e860ff366735de85b56a03095a26efL21-R39

To me it seems like before this commit (i.e. in v0.28), A0 was fixed in terms of A12 using kinematical relations:
https://github.com/flav-io/flavio/blob/7e3d7e969a373c5bd7536fd7c3d43fbf449612e5/flavio/physics/bdecays/formfactors/b_v/bsz.py#L51
A12 was used as parameter, such that changing A12 could have an effect. After the commit, instead A12 is fixed in terms of A0:
https://github.com/flav-io/flavio/blob/7b9eff362f32a631853ea62e9af75c005d985896/flavio/physics/bdecays/formfactors/b_v/bsz.py#L51
A0 is used as parameter, such that changing A0 in v2.00 could have an effect. This might explain @brainygh's observation.

**Comment by DavidMStraub** [comment]
Good point! This change is @dvandyk's fault :) They defined it like that in their 2018 paper (GKvD) and it was changed in flavio to be able to use their numbers.

This change has no numerical impact, but indeed it depends on what the user does.

@brainygh you can check that in flavio v2.0, `flavio.Parameter["B->K* BSZ a0_A12"]` will raise a `KeyError`, while in v0.28, `flavio.Parameter["B->K* BSZ a0_A0"]` will.

I guess, as always, we need to see the code with a minimal working (or breaking) example to understand what's going on.

**Comment by brainygh** [comment]
Dear all,

Thank you very much for the prompt reply. That answers my question. Thank you everyone! I have closed this issue.
