### ISSUE TITLE
NP contributions to R(D(*)) from scalar / tensor operators

### ISSUE THREAD

**Issue by whereforebound** [flav-io/flavio#157]
This issue is related to the implementation of the lepton-flavour universality ratios R(D) and R(D*) in the newest version of flavio. There are analytic expressions for these observables used in the literature, given in terms of the SM values for R(D(*)) and the new-physics contributions which comprise the relevant Wilson coefficients and numerical factors capturing the form factors and kinematics. While the contributions from the vector operator seem to agree very well between Flavio and the analytics, there appear to be sizeable discrepancies for the contributions from the scalar and tensor operator. I appended a pdf file for further illustration.

[flaviovsanalytics.pdf](https://github.com/flav-io/flavio/files/6368772/flaviovsanalytics.pdf)

I am wondering if these discrepancies could arise from a problem with the implementation in Flavio, or if they simply reflect the uncertainties coming along with different form-factor parametrisations? With the potentially related issue #156 regarding the implementation of the SM uncertainties for R(D(*)) having been raised here recently, I assume it might be worth considering the first option.

Many thanks,
Tobias

**Comment by peterstangl** [comment]
The issue with the scalar Wilson coefficients turned out to be a bug and was solved by PR #164.

The differences seen in case of non-zero tensor Wilson coefficients on the other hand seem to just reflects different form factor implementations. In fact, a comparison of flavio and eos shows good agreement:
![CT](https://user-images.githubusercontent.com/10455970/123325566-74d60500-d538-11eb-9a5c-f76ba322a3fd.png)

@whereforebound do you agree and can this issue be closed?

**Comment by whereforebound** [comment]
@peterstangl yes, I agree that these discrepancies are most likely due to different form-factor input. I think the issue can be closed.
