### ISSUE TITLE
ATLAS CMS LHCb combination Bs->mumu 2020 correlations

### ISSUE THREAD

**Issue by cristianfsierraf** [flav-io/flavio#170]
Hello dear flavio team,

I am using the ATLAS CMS LHCb combination coming from LHCb-CONF-2020-002 and I was checking the measurements yaml file you have and I found that you use slightly different central values from the ones reported by the experiment and also you managed to get the correlations with Bd->mumu (not explicitly reported in the experimental paper), I was wondering how exactly did you obtain them (both central values and correlations) and also if I should cite flavio when referring to this combination.

**Comment by peterstangl** [comment]
Hi @cristianfsierraf,

> I found that you use slightly different central values from the ones reported by the experiment

Aren't the central values given in Eq. (12) in http://cds.cern.ch/record/2727207/files/LHCb-CONF-2020-002.pdf actually equal to the values in the flavio yaml file? 

> how exactly did you obtain them (both central values and correlations)

We have extracted this information from the right plot of Fig. 1 in http://cds.cern.ch/record/2727207/files/LHCb-CONF-2020-002.pdf.
To be more precise, inside the 1 sigma region we use a two-dimensional normal distribution that is fitted to the 1 sigma contour. Outside the 1 sigma region we use interpolation between the 1 to 5 sigma contours without assuming a normal distribution since the full likelihood is only approximately a normal distribution close to the central value.

> if I should cite flavio when referring to this combination.

For the combination itself I think it is enough to cite only the original reference, since this combination is just taken from http://cds.cern.ch/record/2727207/files/LHCb-CONF-2020-002.pdf. If you use any part of flavio for your publication, it would still be nice if you cite flavio somewhere in your publication.

It might be interesting for you that a more recent combination of B_s,d->mumu measurements of ATLAS, CMS, and LHCb is available in flavio, which is called `AS combination Bs->mumu 2021` and includes the recent LHCb measurement from 2021. I you use this combination, please also cite the paper in which this combination was done (https://arxiv.org/abs/2103.13370) in addition to the experimental measurements the combination is based on.

**Comment by cristianfsierraf** [comment]
Hello Peter,

Thanks so much for the prompt reply, it all clear now for me, regarding the central values in the yaml file, this are the entries I  have:

> ATLAS CMS LHCb combination Bs->mumu 2020 Gaussian:
>   experiment: ATLAS CMS LHCb
>   inspire: LHCb:2020zud
>   url: http://cds.cern.ch/record/2727207
>   observables:
>     - BR(Bs->mumu)
>     - BR(B0->mumu)
>   values:
>     distribution: multivariate_normal
>     central_value: [2.7164627726229675e-09, 4.997504628427717e-11]
>     standard_deviation: [3.664656167046745e-10, 7.926604121885672e-11]
>     correlation:
>     - [1.0, -0.20884224924764241]
>     - [-0.20884224924764241, 1.0]

where you can see that the central values are not exactly the same as in Eq.12 of  http://cds.cern.ch/record/2727207/files/LHCb-CONF-2020-002.pdf

**Comment by peterstangl** [comment]
Hi @cristianfsierraf,

now I see what you mean concerning the central values. Please note that there are actually two related entries in the `measurements.yml` in flavio:
- `ATLAS CMS LHCb combination Bs->mumu 2020`
  This corresponds to the data extracted from the 2D likelihood contours as described in my previous answer. The central values are equal to those quoted in the experimental publication.
- `ATLAS CMS LHCb combination Bs->mumu 2020 Gaussian`
  This is a fit of a Gaussian distribution to the data of the full numerical distribution in `ATLAS CMS LHCb combination Bs->mumu 2020`. The Gaussian distribution that gives the best fit has central values slightly different from those in the experimental publication.

The Gaussian distribution is required for constructing a `FastLikelihood` that uses Gaussian approximations for all experimental and theoretical uncertainties.

**Comment by cristianfsierraf** [comment]
Oh I see, now makes sense, thanks for the clarification. That means the correlations in *ATLAS CMS LHCb combination Bs->mumu 2020 * are being obtained somehow internally by flavio from the 2D distribution? Because in previous experimental papers they used to provide the correlations but for this combination they didn’t, at least they do not seem to be explicitly stated in http://cds.cern.ch/record/2727207/files/LHCb-CONF-2020-002.pdf

**Comment by peterstangl** [comment]
The correlations in `ATLAS CMS LHCb combination Bs->mumu 2020 Gaussian` are those of the 2D Gaussian distribution that has been fitted to the 2D numerical (non-Gaussian) distribution given in `ATLAS CMS LHCb combination Bs->mumu 2020`, which in turn was extracted from Fig. 1 in http://cds.cern.ch/record/2727207/files/LHCb-CONF-2020-002.pdf as described above.

**Comment by cristianfsierraf** [comment]
Got it! thanks so much Peter, I am mentioning you in the acknowledgments.
