### ISSUE TITLE
Getting set() from flavio.functions.get_dependent_parameters_sm for specific observables

### ISSUE THREAD

**Issue by kys-sheng** [flav-io/flavio#186]
Hi,
I was trying to get the dependent SM parameters of the following observables via `flavio.functions.get_dependent_parameters_sm`:
`BR(B0->K*emu)`
`BR(B+->K*emu)`
`BR(B0->K*mue)`
`BR(B+->K*mue)`
`R(ee->WW)`
`<dR/dtheta>(ee->WW)`
and I get `set()` from all these observables. This can't be right, right? I mean as far as I can tell, all observables should have some dependence on SM parameters such as bottom mass for the semileptonic decays or W mass for the ee->WW process.

I looked up the code, and I noticed that `akeys` did not pick up anything after `obs.prediction_par` was called but I am not sure why. It works find for other observables.

**Comment by DavidMStraub** [comment]
Hi, this is intended behaviour.

For B->Vll', it's because of this:
https://github.com/flav-io/flavio/blob/master/flavio/physics/bdecays/bvll/lfv.py#L58

If all NP WCs vanish, the rate is 0 and no parameters are required.

For ee->WW, the observables are ratios wrt the SM with SM uncertainties neglected (since they are subleading wrt experimental uncertainties), so it only depends on NP WCs in this approximation.

**Comment by kys-sheng** [comment]
Thanks for the explanation!
