### ISSUE TITLE
observable DeltaM_K0?

### ISSUE THREAD

**Issue by f-esser** [flav-io/flavio#253]
Dear authors,

we want to compare the effects of different BSM models on the low-energy observables and noticed that the mass difference in the kaon system, DeltaM_K0, exists only as a parameter and not as an observable like e.g. DeltaM_d and DeltaM_s.
This means that it is not accessible in sm_prediction or np_prediction.
Is there any reason behind this difference and would it be possible to add DeltaM_K0 as an observable too?

Best regards,
Fabian

**Comment by peterstangl** [comment]
The reason is that in contrast to DeltaM_d and DeltaM_s, the prediction of DeltaM_K0 depends on large long-distant contributions that are non-perturbative and therefore difficult to estimate. There has been some progress in lattice QCD in this direction but so far there are only preliminary results and the estimated uncertainties on the Standard Model prediction are around 30%. Without a more precise theory prediction, this observable is not very useful to constrain new physics contributions.
