### ISSUE TITLE
Parameters in bsz.py

### ISSUE THREAD

**Issue by SatoshiMishima** [flav-io/flavio#40]
In physics/bdecays/formfactors/b_v/bsz.py, the resonance parameters are hardcoded: 

mres_bsz['b->d'] = [5.279, 5.324, 5.716];
mres_bsz['b->s'] = [5.367, 5.415, 5.830];

which are slightly different from those listed in BSZ2015 [1503.05534]. Of course, the values are changed slightly when the PDG releases their new averages. Anyway, it would be better to put the above codes in a parameter file, instead of in bsz.py.

**Comment by DavidMStraub** [comment]
Sorry for never following up on this issue, I somehow forgot.

In the meantime, following your suggestion, the resonance masses have been turned into parameters rather than hard-coded values, with names such as `B->K* BCL m0` etc.

As to why there are tiny differences between BSZ2015 and flavio I wasn't able to reconstruct the reason for this. I believe the table in the paper was accidentally not updated to the final numerics.
