### ISSUE TITLE
FlavorKit interface

### ISSUE THREAD

**Issue by SoundSonic1** [flav-io/flavio#41]
Hi,
i am currently trying to calculate the BR of Bs->mumu in the MRSSM with the help of SPheno 
and i can not get past the reading of the Wilson Coeffients. It gets stuck there forever.
Same problem with the MSSM although your test file from 2016 works.
The input file for the MRSSM can be found here: https://pastebin.com/raw/H9vkaK0y
and for the MSSM (new): https://pastebin.com/raw/hYuhK2mQ
The files were created with SARAH-4.12.2 and SPheno v4.0.3.

**Comment by DavidMStraub** [comment]
Hi,

I had a quick look - I believe the parser chokes at the `DECAY1L` blocks. This seems to be a new non-standard notation.

To be honest, this interface has become a bit neglected because behind the courtains we are working on a new exchange format that should make parsing problems like these obsolete.

**Comment by DavidMStraub** [comment]
Although the new [WCxf](https://wcxf.github.io/) interface (the new exchange format mentioned in the previous comment) has been released in the meantime, in bc3556b8004d504fbf61ab1a11e8207042b2440a I pushed a fix to the old FLHA reader that should fix the problem you describe. A new version will be released in a few days.
