### ISSUE TITLE
SM prediction for BR(B+->K+e+e-) vs q2

### ISSUE THREAD

**Issue by palvarezc** [flav-io/flavio#61]
Dear experts,

Trying to obtain a plot of the SM prediction for the BR(B+->K+e+e-) vs q2, I find an strange peaking structure at q2->0, see plot attached (cf. https://arxiv.org/pdf/1509.06235v1.pdf, Fig19). Is this behaviour expected?

[KeeBR.pdf](https://github.com/flav-io/flavio/files/2357478/KeeBR.pdf)

Many thanks in advance!

**Comment by DavidMStraub** [comment]
Dear Paula,

thanks for reporting this! I have traced it back to the NNLO matrix elements of C1 and C2 that were taken from the interpolated results given in [this paper](https://arxiv.org/pdf/0810.4077.pdf). The fact that the structure is not smooth is due to the q2-interpolation in flavio which apparently should use finer steps at low q2. Apart from this  there is the question whether the increase towards q2->0 is actually physical or an artifact of their interpolation. I will investigate and let you know.

**Comment by DavidMStraub** [comment]
(By the way, fortunately the effect is well within the large SM uncertainties and drops out in lepton flavour universality ratios like RK.)

**Comment by DavidMStraub** [comment]
So it turned out that these functions indeed diverge for q2->0. However the value at q2=0 is not actually required for physical observables. So the only problem was that it was a bad idea to use q2=0 as one of the interpolation points. I solved this now by simply interpolating q2*F instead of F now.

I also checked that the result now agrees with another paper, https://arxiv.org/abs/1707.00988.

**Comment by DavidMStraub** [comment]
I just [released a bug fix version](https://github.com/flav-io/flavio/releases/tag/v0.29.2), also on [PyPI](https://pypi.org/project/flavio/0.29.2/). You can upgrade to it as usual with `pip3 install --upgrade flavio`.

**Comment by palvarezc** [comment]
Dear David, 

Many thanks for looking into this. I can confirm that I obtain a smooth behaviour for q2->0 when using the new version.
