### ISSUE TITLE
Problem with matrix elements of meson mixing operators

### ISSUE THREAD

**Issue by MJKirk** [flav-io/flavio#66]
I think the matrix elements of the meson mixing operators (defined in 
[flavio/physics/mesonmixing/amplitude.py](https://github.com/flav-io/flavio/blob/master/flavio/physics/mesonmixing/amplitude.py#L14)) have incorrect factors.

Compare that function to eqs 2.5 - 2.7 in [arXiv:1602.03560](https://arxiv.org/pdf/1602.03560.pdf) (the Fermilab/MILC paper, which at least for B and Bs mixing is where the bag parameters are taken from).
Flavio's SLR operator corresponds to their O4 - Flavio misses out on the d_4 constant.
Similarly, flavio's VLR = -2 * O5, and again misses out the d_5 constant, which here is a large correction compared to the mass ratio.
(The factors as given by flavio currently match older lattice papers, e.g. [this ETMC paper](https://arxiv.org/pdf/1308.1851.pdf), but I agree with F/MILC that their new coefficients are correct.)

And finally, I believe the overall sign of the TLL operator is wrong, as by Fierz TLL = -4 O2 -8 O3, and O2 has a negative overall coefficient while O3 has a positive one (c_2 = -5/12, c_3 = +1/12 from F/MILC).

**Comment by DavidMStraub** [comment]
Hi Matthew,

thanks for reporting this!

I had no idea that FNAL/MILC have changed the definition of some of the bag parameters. I find that totally shocking. I'm not sure what you mean by "their new coefficients are correct" - this is simply a definition/convention. Sure, it might be that in the "old" convention the VIA limit does not correspond to B=1. But who cares about the VIA anyway? I find this very annoying, and also problematic for flavio, where it is supposed to be easy to change values of parameters. In fact in older flavio versions, ETM was used - and it does not seem right to change the definition of some internal parameters from version to version. So maybe I'll have to change the numerical values of the FNAL matrix elements. Incomprehensible to me why these guys can't agree on common conventions.  In any case, great you noticed! Should have read their paper more carefully.

As for TLL, I think you're right. To be honest I simply took that from a prominent physicist's diploma thesis :) and indeed I think it's wrong there. Your Fierz relation agrees with the  one in my conventions for sigma_munu. I suspect this error goes back to https://arxiv.org/pdf/hep-ph/0102316.pdf, where the authors use a crazy convention for sigma_munu that flips the sign of the tensor operator.

**Comment by DavidMStraub** [comment]
@MJKirk, I thought about this and read some literature. I think changing the conventions to the FNAL conventions is not a good idea.

First and foremost, this function is used also for K and D mixing matrix elements. The references for those MEs use the other convention, so changing the function is not an option.

Secondly, I found a very good discussion of this issue in https://arxiv.org/pdf/hep-lat/9806016.pdf, namely the page following eq. (11). There they explain that the convention without the additional terms (which are formally of higher order in the chiral expansion) would lead to a much more complicated scaling behaviour.

Finally, since the lattice is completely unrelated to the VSA and the bag parameters are just based on a convention, I see no advantage in changing the definition and I really dislike that FNAL did that. In flavio, the only option is to change the numerical values of the bag parameters.

**Comment by DavidMStraub** [comment]
By the way, in reviewing the function I found another problem, namely that the quark masses were not run to the appropriate scale. This is now fixed in 6b5990a4c3aae064e09ce70a69c9905709865da6. Numerically, this only makes a difference for D mixing though.
